<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import PageHeader from '@/components/PageHeader.vue'; import StatusTag from '@/components/StatusTag.vue'; import type { Project } from '@/types'; import { createProject, deleteProject, getProjects, updateProject } from '@/api/projects'; import { ElMessage, ElMessageBox } from 'element-plus'
const loading=ref(false),dialog=ref(false),rows=ref<Project[]>([]),total=ref(0);const query=reactive({current:1,size:10,keyword:'',status:''});const form=reactive<Project>({id:0,name:'',teacher:'',startDate:'',endDate:'',status:'ACTIVE'})
async function load(){loading.value=true;try{const p=await getProjects(query);rows.value=p.records;total.value=p.total}catch{rows.value=[]}finally{loading.value=false}}
function reset(){query.keyword='';query.status='';query.current=1;load()} function open(row?:Project){Object.assign(form,row||{id:0,name:'',teacher:'',startDate:'',endDate:'',status:'ACTIVE'});dialog.value=true}
async function save(){if(!form.name||!form.teacher)return ElMessage.warning('请填写项目名称和负责教师');if(form.id)await updateProject(form.id,form);else await createProject(form);ElMessage.success('保存成功');dialog.value=false;load()}
async function remove(row:Project){await ElMessageBox.confirm(`确认删除“${row.name}”吗？`,'删除项目',{type:'warning'});await deleteProject(row.id);ElMessage.success('删除成功');load()}
onMounted(load)
</script>
<template><div><PageHeader title="实训项目管理" description="维护证书对应的实训项目与时间范围"><el-button type="primary" @click="open()">新增项目</el-button></PageHeader><section class="panel"><div class="toolbar"><el-input v-model="query.keyword" placeholder="项目名称或教师" clearable style="width:260px" @keyup.enter="query.current=1;load()"/><el-select v-model="query.status" placeholder="状态" clearable style="width:140px"><el-option label="进行中" value="ACTIVE"/><el-option label="已完成" value="COMPLETED"/></el-select><el-button type="primary" @click="query.current=1;load()">查询</el-button><el-button @click="reset">重置</el-button></div><el-table v-loading="loading" :data="rows" empty-text="暂无项目数据"><el-table-column prop="name" label="项目名称" min-width="220"/><el-table-column prop="teacher" label="负责教师"/><el-table-column prop="startDate" label="开始日期"/><el-table-column prop="endDate" label="结束日期"/><el-table-column label="状态"><template #default="s"><StatusTag :value="s.row.status"/></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.current" v-model:page-size="query.size" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @change="load"/></div></section><el-dialog v-model="dialog" :title="form.id?'编辑项目':'新增项目'" width="520"><el-form label-position="top"><el-form-item label="项目名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="负责教师" required><el-input v-model="form.teacher"/></el-form-item><div class="form-grid"><el-form-item label="开始日期"><el-date-picker v-model="form.startDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="form.endDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></div><el-form-item label="状态"><el-select v-model="form.status"><el-option label="进行中" value="ACTIVE"/><el-option label="已完成" value="COMPLETED"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>